Fixed compile error
error: C1128: number of sections exceeded object file format limit: compile with /bigobj

There is nothing criminal in the code, but a large obj file is generated. Perhaps the code can be optimized to reduce the output file, or maybe this is due to the inclusion of large interfaces such as NotationInteraction