appimageupdatetool: downgrade to older version
avoids needing gpgme which, in order to build, requires _FILE_OFFSET_BITS=64 which causes issues with linking to system libz.so.1

/usr/bin/ld: libzsync2_standalone.a(zsclient.cpp.o): undefined reference to symbol 'gzopen64@@ZLIB_1.2.3.3'
/usr/bin/ld: /lib/arm-linux-gnueabihf/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

https://github.com/AppImageCommunity/AppImageUpdate/issues/230