Windows: Fix build error C2872: 'Uri': ambiguous symbol
On my Windows 11 machine, winrt::Windows::Foundation::Uri conflicts
with muse::Uri when included in a Unity Build.