missing header
src/palette/view/widgets/palettewidget.cpp:
In member function ‘void mu::palette::PaletteWidget::applyElementAtIndex(int, Qt::KeyboardModifiers)’:
src/palette/view/widgets/palettewidget.cpp:460:28:
error: invalid use of incomplete type ‘class QWindow’
  460 |     mainWindow()->qWindow()->requestActivate();
      |                            ^~

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>