Missing includes
>src/framework/ui/view/internal/widgetdialogadapter.cpp:97
>:21: error: cannot initialize object parameter of type 'QObject'
> with an expression of type 'muse::ui::WidgetDialogAdapter'
>   97 |     return QObject::eventFilter(watched, event);
>      |                     ^~~~~~~~~~~

>src/framework/ui/view/internal/widgetdialogadapter.cpp:86
>:37: error: member access into incomplete type 'QWindow'
>   86 |             m_dialog->windowHandle()->setTransientParent(m_window);
>      |                                     ^
>/usr/include/qt6/QtGui/qwindowdefs.h:19:7: note: forward declaration of 'QWindow'
>   19 | class QWindow;
>      |       ^

>src/notation/internal/notationactioncontroller.cpp:2236:5
>2: error: use of undeclared identifier 'QGuiApplication'; did you mean 'QApplication'?
> 2236 |     QGuiApplication::applicationState() == Qt::ApplicationActive;
>      |     ^~~~~~~~~~~~~~~
>      |     QApplication

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>